version: '2'

services:
  consoleapp1:
    image: user/consoleapp1:dev
    build:
      args:
        source: obj/Docker/empty/
    volumes:
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
