version: '2'

services:
  dockersolutionsupport:
    image: user/dockersolutionsupport
    build:
      context: .
      dockerfile: Dockerfile
      args:
        source: ${DOCKER_BUILD_SOURCE}
    ports:
      - "80"
