version: '2'

services:
  dockersolutionsupport:
    image: user/dockersolutionsupport
    build:
      context: DockerSolutionSupport
      dockerfile: Dockerfile
    ports:
      - "80"
  webapi:
    image: user/webapi
    build:
      context: WebApi
      dockerfile: Dockerfile
    ports:
      - "80"
