version: '2'

services:
  dockersolutionsupport:
    image: user/dockersolutionsupport
    build:
      context: src/DockerSolutionSupport
      dockerfile: Dockerfile
    ports:
      - "80"
  webapi:
    image: user/webapi
    build:
      context: src/WebApi
      dockerfile: Dockerfile
    ports:
      - "80"
  consoleapp1:
    image: user/consoleapp1
    build:
      context: src/ConsoleApp1
      dockerfile: Dockerfile
